language: python
python: 3.4
sudo: required
services:
  - docker
install:
  - docker build -t lop.io .
before_script:
  - pip install flake8
  - flake8 --exclude=migrations .
script:
  - docker run --privileged -t lop.io test
