apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      run: web
    name: web
  spec:
    replicas: 1
    selector:
      run: web
    template:
      metadata:
        labels:
          run: web
      spec:
        containers:
        - image: corey/lop.farm
          imagePullPolicy: IfNotPresent
          name: web
          ports:
          - containerPort: 8000
            protocol: TCP
        dnsPolicy: ClusterFirst
        restartPolicy: Always
