apiVersion: v1
kind: Service
metadata:
  labels:
    run: web
  name: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    run: web
  loadBalancerIP: 104.197.103.20
